id: P005456
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 11:51:30.390283
source_metadata:
  id: bdr:W27513
  title: གསོལ་འདེབས་ལེའུ་བདུན་པ་དང་བསམ་པ་ལྷུན་གྲུབ་རྟེན་བསྐྱེད་དང་བཅས་པ
  author: ''
  volumes:
    5a1449acd536443db34938aa483fadbf:
      image_group_id: I4472
      title: ''
      volume_number: 1
      total_pages: 74
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
