id: P005456
initial_creation_type: ocr
source_metadata:
  id: bdr:W27513
  title: གསོལ་འདེབས་ལེའུ་བདུན་པ་དང་བསམ་པ་ལྷུན་གྲུབ་རྟེན་བསྐྱེད་དང་བཅས་པ
  author: ''
  volumes:
    5a1449acd536443db34938aa483fadbf:
      image_group_id: I4472
      title: ''
      volume_number: 1
      total_pages: 74
